# ETL?
## Extract
원시 데이터를 소스 위치에서 스테이징 영역으로 복사하거나 내보냄

다양한 소스에서 데이터를 추출할 수 있고, 이는 정형 또는 비정형

- 소스의 유형의 예시
    - SQL 또는 NoSQL 서버
    - CRM 및 ERP 시스템
    - 플랫 파일
    - 이메일
    - 웹페이지

## Transform
스테이징 영역에서 원시 데이터를 처리함

의도하는 분석 사용 사례에 맞게 변환 및 통합

다음과 같은 작업을 포함할 수 있음
- 데이터를 필터링, 정제, 중복 제거, 유효성 검사 및 인증
- 원시 데이터를 기반으로 계산, 번역 또는 요약을 수행합니다. 여기에는 일관성을 위해 행 및 열 머리글 변경, 통화 또는 기타 측정 단위 변환, 텍스트 문자열 편집 등이 포함될 수 있음
- 데이터 품질 및 규정 준수를 보장하기 위해 감사를 수행
- 업계 또는 정부 규제 기관에서 관리하는 데이터를 제거, 암호화 또는 보호
- 대상 데이터 웨어하우스의 스키마와 일치하도록 데이터를 테이블 또는 결합된 테이블로 포맷

## Load
변환된 데이터를 스테이징 영역에서 대상 데이터 웨어하우스로 이동
일반적으로 모든 데이터를 처음 로드한 다음 증분 데이터 변경 사항을 주기적으로 로드
드물게는 웨어하우스에서 데이터를 삭제하고 교체하는 전체 새로 고침을 수행하는 작업이 포함
일반적으로 ETL은 소스 시스템과 데이터 웨어하우스의 트래픽이 가장 적은 근무 외 시간에 이루어짐

In [12]:
import requests
from bs4 import BeautifulSoup as bs
import pandas as pd
import numpy as np

In [13]:
url = 'https://en.wikipedia.org/wiki/List_of_countries_by_GDP_%28nominal%29'
gdp_page = requests.get(url)
soup = bs(gdp_page.text, "html.parser")

In [14]:
gdps = []

# get table elements
trs = soup.select('table.wikitable > tbody > tr')

for tr in trs:
    td = tr.select('td')
    if td:
        country = td[0].text.strip()
        gdp = td[1].text.strip().replace(',','')
        if gdp == '—': # WARNING: this is not dash symbol
            gdp = '0' # 0 means NULL
        gdps.append((country, int(gdp) / 1000)) # from million to billion

gdps

[('World', 109529.216),
 ('United States', 28781.083),
 ('China', 18532.633),
 ('Germany', 4591.1),
 ('Japan', 4110.452),
 ('India', 3937.011),
 ('United Kingdom', 3495.261),
 ('France', 3130.014),
 ('Brazil', 2331.391),
 ('Italy', 2328.028),
 ('Canada', 2242.182),
 ('Russia', 2056.844),
 ('Mexico', 2017.025),
 ('Australia', 1790.348),
 ('South Korea', 1760.947),
 ('Spain', 1647.114),
 ('Indonesia', 1475.69),
 ('Netherlands', 1142.513),
 ('Turkey', 1113.561),
 ('Saudi Arabia', 1106.015),
 ('Switzerland', 938.458),
 ('Poland', 844.623),
 ('Taiwan', 802.958),
 ('Belgium', 655.192),
 ('Sweden', 623.048),
 ('Argentina', 604.26),
 ('Ireland', 564.02),
 ('Thailand', 548.89),
 ('Austria', 540.887),
 ('Israel', 530.664),
 ('United Arab Emirates', 527.796),
 ('Norway', 526.951),
 ('Singapore', 525.228),
 ('Philippines', 471.516),
 ('Vietnam', 465.814),
 ('Iran', 464.181),
 ('Bangladesh', 455.162),
 ('Malaysia', 445.519),
 ('Denmark', 409.989),
 ('Hong Kong', 406.775),
 ('Colombia', 386.076),
 ('South Africa', 373.233),
 ('Romania', 369.971),
 ('Egypt', 347.594),
 ('Pakistan', 338.237),
 ('Chile', 333.76),
 ('Czech Republic', 325.88),
 ('Finland', 308.055),
 ('Portugal', 298.949),
 ('Kazakhstan', 296.74),
 ('Peru', 282.458),
 ('Algeria', 266.78),
 ('Iraq', 265.894),
 ('New Zealand', 257.625),
 ('Nigeria', 252.738),
 ('Greece', 250.276),
 ('Qatar', 244.686),
 ('Hungary', 223.413),
 ('Ethiopia', 205.13),
 ('Ukraine', 188.943),
 ('Kuwait', 160.397),
 ('Morocco', 152.377),
 ('Cuba', 0.0),
 ('Slovakia', 140.808),
 ('Dominican Republic', 127.356),
 ('Ecuador', 121.592),
 ('Puerto Rico', 117.763),
 ('Guatemala', 110.035),
 ('Oman', 108.927),
 ('Bulgaria', 107.933),
 ('Kenya', 104.001),
 ('Venezuela', 102.328),
 ('Uzbekistan', 97.956),
 ('Costa Rica', 96.058),
 ('Angola', 92.123),
 ('Luxembourg', 88.556),
 ('Croatia', 88.076),
 ('Panama', 87.347),
 ('Ivory Coast', 86.911),
 ('Uruguay', 82.605),
 ('Turkmenistan', 81.896),
 ('Serbia', 81.873),
 ('Lithuania', 81.17),
 ('Tanzania', 79.605),
 ('Azerbaijan', 78.749),
 ('Ghana', 75.244),
 ('Sri Lanka', 74.846),
 ('DR Congo', 73.761),
 ('Slovenia', 72.101),
 ('Belarus', 69.048),
 ('Myanmar', 68.006),
 ('Uganda', 56.31),
 ('Tunisia', 54.708),
 ('Macau', 54.677),
 ('Jordan', 53.57),
 ('Cameroon', 53.205),
 ('Bolivia', 49.334),
 ('Libya', 48.221),
 ('Bahrain', 46.79),
 ('Paraguay', 45.817),
 ('Latvia', 45.466),
 ('Cambodia', 45.15),
 ('Nepal', 44.179),
 ('Estonia', 43.486),
 ('Honduras', 37.355),
 ('Senegal', 35.45),
 ('El Salvador', 35.333),
 ('Zimbabwe', 34.405),
 ('Cyprus', 34.221),
 ('Iceland', 33.338),
 ('Georgia', 32.865),
 ('Papua New Guinea', 31.716),
 ('Zambia', 29.872),
 ('Bosnia and Herzegovina', 29.078),
 ('Trinidad and Tobago', 28.365),
 ('Sudan', 26.865),
 ('Guinea', 25.447),
 ('Albania', 25.431),
 ('Armenia', 25.408),
 ('Haiti', 24.046),
 ('Mozambique', 22.975),
 ('Malta', 22.737),
 ('Mongolia', 21.943),
 ('Burkina Faso', 21.902),
 ('Lebanon', 21.78),
 ('Mali', 21.662),
 ('Botswana', 21.418),
 ('Benin', 21.371),
 ('Guyana', 21.178),
 ('Gabon', 21.013),
 ('Jamaica', 20.098),
 ('Nicaragua', 18.829),
 ('Niger', 18.816),
 ('Chad', 18.697),
 ('Palestine', 18.602),
 ('Moldova', 18.356),
 ('Yemen', 16.94),
 ('Madagascar', 16.465),
 ('Mauritius', 16.359),
 ('North Macedonia', 15.873),
 ('Brunei', 15.51),
 ('Congo', 15.501),
 ('Laos', 15.19),
 ('North Korea', 0.0),
 ('Afghanistan', 14.467),
 ('Bahamas', 14.39),
 ('Rwanda', 13.701),
 ('Kyrgyzstan', 13.599),
 ('Tajikistan', 12.953),
 ('Somalia', 12.804),
 ('Namibia', 12.765),
 ('Kosovo', 11.318),
 ('Malawi', 11.241),
 ('Equatorial Guinea', 10.708),
 ('Mauritania', 10.628),
 ('Togo', 9.832),
 ('New Caledonia', 0.0),
 ('Syria', 0.0),
 ('Monaco', 0.0),
 ('Montenegro', 8.01),
 ('Liechtenstein', 0.0),
 ('Bermuda', 0.0),
 ('Maldives', 7.199),
 ('Barbados', 6.863),
 ('Cayman Islands', 0.0),
 ('South Sudan', 6.517),
 ('French Polynesia', 0.0),
 ('Fiji', 5.801),
 ('Eswatini', 5.085),
 ('Liberia', 4.754),
 ('Sierra Leone', 4.558),
 ('Djibouti', 4.364),
 ('Suriname', 4.337),
 ('Aruba', 4.069),
 ('Andorra', 3.897),
 ('Belize', 3.296),
 ('Greenland', 0.0),
 ('Bhutan', 3.11),
 ('Curaçao', 0.0),
 ('Burundi', 3.075),
 ('Central African Republic', 2.81),
 ('Cape Verde', 2.718),
 ('Gambia', 2.694),
 ('Saint Lucia', 2.582),
 ('Lesotho', 2.395),
 ('Eritrea', 0.0),
 ('Zanzibar', 0.0),
 ('Seychelles', 2.203),
 ('Guinea-Bissau', 2.151),
 ('Antigua and Barbuda', 2.127),
 ('San Marino', 2.033),
 ('East Timor', 1.992),
 ('Solomon Islands', 1.707),
 ('Sint Maarten', 0.0),
 ('British Virgin Islands', 0.0),
 ('Comoros', 1.422),
 ('Grenada', 1.406),
 ('Vanuatu', 1.289),
 ('Turks and Caicos Islands', 0.0),
 ('Saint Kitts and Nevis', 1.134),
 ('Saint Vincent and the Grenadines', 1.128),
 ('Samoa', 1.024),
 ('São Tomé and Príncipe', 0.751),
 ('Dominica', 0.708),
 ('Tonga', 0.581),
 ('Micronesia', 0.484),
 ('Anguilla', 0.0),
 ('Kiribati', 0.311),
 ('Palau', 0.308),
 ('Marshall Islands', 0.305),
 ('Cook Islands', 0.0),
 ('Nauru', 0.161),
 ('Montserrat', 0.0),
 ('Tuvalu', 0.066)]

In [16]:
column_name = ('Country', 'GDP')
df = pd.DataFrame(gdps, columns=column_name)
df_only_countries = df[df['Country']!='World'].sort_values(by='GDP', ascending=False).replace(0, np.NaN)
df_only_countries

           Country        GDP
1    United States  28781.083
2            China  18532.633
3          Germany   4591.100
4            Japan   4110.452
5            India   3937.011
..             ...        ...
158         Monaco        NaN
157          Syria        NaN
156  New Caledonia        NaN
143    North Korea        NaN
160  Liechtenstein        NaN

[213 rows x 2 columns]

In [17]:
# json 파일로 저장
df_only_countries.to_json('Countries_by_GDP.json', orient='records', indent=4)