In [6]:
import sqlite3
import pandas as pd

In [8]:
def run_sql(statement, path='chinook.db'):
    try:
        with sqlite3.connect(path) as conn:
            cursor = conn.cursor()
            cursor.execute(statement)
            
            if statement.strip().lower().startswith("select"):
                rows = cursor.fetchall()
                columns = [description[0] for description in cursor.description]
                df = pd.DataFrame(rows, columns=columns)
                return df
            # conn.commit()
    except sqlite3.Error as e:
        return e

# Select all the records

In [11]:
statement = """
    SELECT * FROM Customers
"""

run_sql(statement)

,CustomerId,FirstName,LastName,Company,Address,City,State,Country,PostalCode,Phone,Fax,Email,SupportRepId
0,1,Luís,Gonçalves,Embraer - Empresa Brasileira de Aeronáutica S.A.,"Av. Brigadeiro Faria Lima, 2170",São José dos Campos,SP,Brazil,12227-000,+55 (12) 3923-5555,+55 (12) 3923-5566,luisg@embraer.com.br,3
1,2,Leonie,Köhler,BaekSu,Theodor-Heuss-Straße 34,Stuttgart,None,Germany,70174,+49 0711 2842222,None,leonekohler@surfeu.de,5
2,3,François,Tremblay,BaekSu,1498 rue Bélanger,Montréal,QC,Canada,H2G 1A7,+1 (514) 721-4711,None,ftremblay@gmail.com,3
3,4,Bjørn,Hansen,BaekSu,Ullevålsveien 14,Oslo,None,Norway,0171,+47 22 44 22 22,None,bjorn.hansen@yahoo.no,4
4,5,František,Wichterlová,JetBrains s.r.o.,Klanova 9/506,Prague,None,Czech Republic,14700,+420 2 4172 5555,+420 2 4172 5555,frantisekw@jetbrains.com,4
5,6,Helena,Holý,BaekSu,Rilská 3174/6,Prague,None,Czech Republic,14300,+420 2 4177 0449,None,hholy@gmail.com,5
6,7,Astrid,Gruber,BaekSu,"Rotenturmstraße 4, 1010 Innere Stadt",Vienne,None,Austria,1010,+43 01 5134505,None,astrid.gruber@apple.at,5
7,8,Daan,Peeters,BaekSu,Grétrystraat 63,Brussels,None,Belgium,1000,+32 02 219 03 03,None,daan_peeters@apple.be,4
8,9,Kara,Nielsen,BaekSu,Sønder Boulevard 51,Copenhagen,None,Denmark,1720,+453 3331 9991,None,kara.nielsen@jubii.dk,4
9,10,Eduardo,Martins,Woodstock Discos,"Rua Dr. Falcão Filho, 155",São Paulo,SP,Brazil,01007-010,+55 (11) 3033-5446,+55 (11) 3033-4564,eduardo@woodstock.com.br,4
10,11,Alexandre,Rocha,Banco do Brasil S.A.,"Av. Paulista, 2022",São Paulo,SP,Brazil,01310-200,+55 (11) 3055-3278,+55 (11) 3055-8131,alero@uol.com.br,5
11,12,Roberto,Almeida,Riotur,"Praça Pio X, 119",Rio de Janeiro,RJ,Brazil,20040-020,+55 (21) 2271-7000,+55 (21) 2271-7070,roberto.almeida@riotur.gov.br,3
12,13,Fernanda,Ramos,BaekSu,Qe 7 Bloco G,Brasília,DF,Brazil,71020-677,+55 (61) 3363-5547,+55 (61) 3363-7855,fernadaramos4@uol.com.br,4
13,14,Mark,Philips,Telus,8210 111 ST NW,Edmonton,AB,Canada,T6G 2C7,+1 (780) 434-4554,+1 (780) 434-5565,mphilips12@shaw.ca,5
14,15,Jennifer,Peterson,Rogers Canada,700 W Pender Street,Vancouver,BC,Canada,V6C 1G8,+1 (604) 688-2255,+1 (604) 688-8756,jenniferp@rogers.ca,3
15,16,Frank,Harris,Google Inc.,1600 Amphitheatre Parkway,Mountain View,CA,USA,94043-1351,+1 (650) 253-0000,+1 (650) 253-0000,fharris@google.com,4
16,17,Jack,Smith,Microsoft Corporation,1 Microsoft Way,Redmond,WA,USA,98052-8300,+1 (425) 882-8080,+1 (425) 882-8081,jacksmith@microsoft.com,5
17,18,Michelle,Brooks,BaekSu,627 Broadway,New York,NY,USA,10012-2612,+1 (212) 221-3546,+1 (212) 221-4679,michelleb@aol.com,3
18,19,Tim,Goyer,Apple Inc.,1 Infinite Loop,Cupertino,CA,USA,95014,+1 (408) 996-1010,+1 (408) 996-1011,tgoyer@apple.com,3
19,20,Dan,Miller,BaekSu,541 Del Medio Avenue,Mountain View,CA,USA,94040-111,+1 (650) 644-3358,None,dmiller@comcast.com,4
20,21,Kathy,Chase,BaekSu,801 W 4th Street,Reno,NV,USA,89503,+1 (775) 223-7665,None,kachase@hotmail.com,5
21,22,Heather,Leacock,BaekSu,120 S Orange Ave,Orlando,FL,USA,32801,+1 (407) 999-7788,None,hleacock@gmail.com,4
22,23,John,Gordon,BaekSu,69 Salem Street,Boston,MA,USA,2113,+1 (617) 522-1333,None,johngordon22@yahoo.com,4
23,24,Frank,Ralston,BaekSu,162 E Superior Street,Chicago,IL,USA,60611,+1 (312) 332-3232,None,fralston@gmail.com,3
24,25,Victor,Stevens,BaekSu,319 N. Frances Street,Madison,WI,USA,53703,+1 (608) 257-0597,None,vstevens@yahoo.com,5
25,26,Richard,Cunningham,BaekSu,2211 W Berry Street,Fort Worth,TX,USA,76110,+1 (817) 924-7272,None,ricunningham@hotmail.com,4
26,27,Patrick,Gray,BaekSu,1033 N Park Ave,Tucson,AZ,USA,85719,+1 (520) 622-4200,None,patrick.gray@aol.com,4
27,28,Julia,Barnett,BaekSu,302 S 700 E,Salt Lake City,UT,USA,84102,+1 (801) 531-7272,None,jubarnett@gmail.com,5
28,29,Robert,Brown,BaekSu,796 Dundas Street West,Toronto,ON,Canada,M6J 1V1,+1 (416) 363-8888,None,robbrown@shaw.ca,3
29,30,Edward,Francis,BaekSu,230 Elgin Street,Ottawa,ON,Canada,K2P 1L7,+1 (613) 234-3322,None,edfrancis@yachoo.ca,3
30,31,Martha,Silk,BaekSu,194A Chain Lake Drive,Halifax,NS,Canada,B3S 1C5,+1 (902) 450-0450,None,marthasilk@gmail.com,5
31,32,Aaron,Mitchell,BaekSu,696 Osborne Street,Winnipeg,MB,Canada,R3L 2B9,+1 (204) 452-6452,None,aaronmitchell@yahoo.ca,4
32,33,Ellie,Sullivan,BaekSu,5112 48 Street,Yellowknife,NT,Canada,X1A 1N6,+1 (867) 920-2233,None,ellie.sullivan@shaw.ca,3
33,34,João,Fernandes,BaekSu,Rua da Assunção 53,Lisbon,None,Portugal,None,+351 (213) 466-111,None,jfernandes@yahoo.pt,4
34,35,Madalena,Sampaio,BaekSu,"Rua dos Campeões Europeus de Viena, 4350",Porto,None,Portugal,None,+351 (225) 022-448,None,masampaio@sapo.pt,4
35,36,Hannah,Schneider,BaekSu,Tauentzienstraße 8,Berlin,None,Germany,10789,+49 030 26550280,None,hannah.schneider@yahoo.de,5
36,37,Fynn,Zimmermann,BaekSu,Berger Straße 10,Frankfurt,None,Germany,60316,+49 069 40598889,None,fzimmermann@yahoo.de,3
37,38,Niklas,Schröder,BaekSu,Barbarossastraße 19,Berlin,None,Germany,10779,+49 030 2141444,None,nschroder@surfeu.de,3
38,39,Camille,Bernard,BaekSu,"4, Rue Milton",Paris,None,France,75009,+33 01 49 70 65 65,None,camille.bernard@yahoo.fr,4
39,40,Dominique,Lefebvre,BaekSu,"8, Rue Hanovre",Paris,None,France,75002,+33 01 47 42 71 71,None,dominiquelefebvre@gmail.com,4
40,41,Marc,Dubois,BaekSu,"11, Place Bellecour",Lyon,None,France,69002,+33 04 78 30 30 30,None,marc.dubois@hotmail.com,5
41,42,Wyatt,Girard,BaekSu,"9, Place Louis Barthou",Bordeaux,None,France,33000,+33 05 56 96 96 96,None,wyatt.girard@yahoo.fr,3
42,43,Isabelle,Mercier,BaekSu,"68, Rue Jouvence",Dijon,None,France,21000,+33 03 80 73 66 99,None,isabelle_mercier@apple.fr,3
43,44,Terhi,Hämäläinen,BaekSu,Porthaninkatu 9,Helsinki,None,Finland,00530,+358 09 870 2000,None,terhi.hamalainen@apple.fi,3
44,45,Ladislav,Kovács,BaekSu,Erzsébet krt. 58.,Budapest,None,Hungary,H-1073,None,None,ladislav_kovacs@apple.hu,3
45,46,Hugh,O'Reilly,BaekSu,3 Chatham Street,Dublin,Dublin,Ireland,None,+353 01 6792424,None,hughoreilly@apple.ie,3
46,47,Lucas,Mancini,BaekSu,"Via Degli Scipioni, 43",Rome,RM,Italy,00192,+39 06 39733434,None,lucas.mancini@yahoo.it,5
47,48,Johannes,Van der Berg,BaekSu,Lijnbaansgracht 120bg,Amsterdam,VV,Netherlands,1016,+31 020 6223130,None,johavanderberg@yahoo.nl,5
48,49,Stanisław,Wójcik,BaekSu,Ordynacka 10,Warsaw,None,Poland,00-358,+48 22 828 37 39,None,stanisław.wójcik@wp.pl,4
49,50,Enrique,Muñoz,BaekSu,C/ San Bernardo 85,Madrid,None,Spain,28015,+34 914 454 454,None,enrique_munoz@yahoo.es,5
50,51,Joakim,Johansson,BaekSu,Celsiusg. 9,Stockholm,None,Sweden,11230,+46 08-651 52 52,None,joakim.johansson@yahoo.se,5
51,52,Emma,Jones,BaekSu,202 Hoxton Street,London,None,United Kingdom,N1 5LH,+44 020 7707 0707,None,emma_jones@hotmail.com,3
52,53,Phil,Hughes,BaekSu,113 Lupus St,London,None,United Kingdom,SW1V 3EN,+44 020 7976 5722,None,phil.hughes@gmail.com,3
53,54,Steve,Murray,BaekSu,110 Raeburn Pl,Edinburgh,None,United Kingdom,EH4 1HH,+44 0131 315 3300,None,steve.murray@yahoo.uk,5
54,55,Mark,Taylor,BaekSu,421 Bourke Street,Sidney,NSW,Australia,2010,+61 (02) 9332 3633,None,mark.taylor@yahoo.au,4
55,56,Diego,Gutiérrez,BaekSu,307 Macacha Güemes,Buenos Aires,None,Argentina,1106,+54 (0)11 4311 4333,None,diego.gutierrez@yahoo.ar,4
56,57,Luis,Rojas,BaekSu,"Calle Lira, 198",Santiago,None,Chile,None,+56 (0)2 635 4444,None,luisrojas@yahoo.cl,5
57,58,Manoj,Pareek,BaekSu,"12,Community Centre",Delhi,None,India,110017,+91 0124 39883988,None,manoj.pareek@rediff.com,3
58,59,Puja,Srivastava,BaekSu,"3,Raj Bhavan Road",Bangalore,None,India,560001,+91 080 22289999,None,puja_srivastava@yahoo.in,3

# SELECT

In [14]:
statement = """
    SELECT LastName, City FROM Customers
"""

run_sql(statement)

        LastName                 City
0      Gonçalves  São José dos Campos
1         Köhler            Stuttgart
2       Tremblay             Montréal
3         Hansen                 Oslo
4    Wichterlová               Prague
5           Holý               Prague
6         Gruber               Vienne
7        Peeters             Brussels
8        Nielsen           Copenhagen
9        Martins            São Paulo
10         Rocha            São Paulo
11       Almeida       Rio de Janeiro
12         Ramos             Brasília
13       Philips             Edmonton
14      Peterson            Vancouver
15        Harris        Mountain View
16         Smith              Redmond
17        Brooks             New York
18         Goyer            Cupertino
19        Miller        Mountain View
20         Chase                 Reno
21       Leacock              Orlando
22        Gordon               Boston
23       Ralston              Chicago
24       Stevens              Madison
25    Cunningham           Fort Worth
26          Gray               Tucson
27       Barnett       Salt Lake City
28         Brown              Toronto
29       Francis               Ottawa
30          Silk              Halifax
31      Mitchell             Winnipeg
32      Sullivan          Yellowknife
33     Fernandes               Lisbon
34       Sampaio                Porto
35     Schneider               Berlin
36    Zimmermann            Frankfurt
37      Schröder               Berlin
38       Bernard                Paris
39      Lefebvre                Paris
40        Dubois                 Lyon
41        Girard             Bordeaux
42       Mercier                Dijon
43    Hämäläinen             Helsinki
44        Kovács             Budapest
45      O'Reilly               Dublin
46       Mancini                 Rome
47  Van der Berg            Amsterdam
48        Wójcik               Warsaw
49         Muñoz               Madrid
50     Johansson            Stockholm
51         Jones               London
52        Hughes               London
53        Murray           Edinburgh
54        Taylor               Sidney
55     Gutiérrez         Buenos Aires
56         Rojas             Santiago
57        Pareek                Delhi
58    Srivastava            Bangalore

# SELECT DISTINCT

In [17]:
statement = """
    SELECT DISTINCT Country FROM Customers
"""

run_sql(statement)

           Country
0           Brazil
1          Germany
2           Canada
3           Norway
4   Czech Republic
5          Austria
6          Belgium
7          Denmark
8              USA
9         Portugal
10          France
11         Finland
12         Hungary
13         Ireland
14           Italy
15     Netherlands
16          Poland
17           Spain
18          Sweden
19  United Kingdom
20       Australia
21       Argentina
22           Chile
23           India

# WHERE

In [20]:
statement = """
    SELECT * FROM Customers
    WHERE Country='Brazil'
"""

run_sql(statement)

,CustomerId,FirstName,LastName,Company,Address,City,State,Country,PostalCode,Phone,Fax,Email,SupportRepId
0,1,Luís,Gonçalves,Embraer - Empresa Brasileira de Aeronáutica S.A.,"Av. Brigadeiro Faria Lima, 2170",São José dos Campos,SP,Brazil,12227-000,+55 (12) 3923-5555,+55 (12) 3923-5566,luisg@embraer.com.br,3
1,10,Eduardo,Martins,Woodstock Discos,"Rua Dr. Falcão Filho, 155",São Paulo,SP,Brazil,01007-010,+55 (11) 3033-5446,+55 (11) 3033-4564,eduardo@woodstock.com.br,4
2,11,Alexandre,Rocha,Banco do Brasil S.A.,"Av. Paulista, 2022",São Paulo,SP,Brazil,01310-200,+55 (11) 3055-3278,+55 (11) 3055-8131,alero@uol.com.br,5
3,12,Roberto,Almeida,Riotur,"Praça Pio X, 119",Rio de Janeiro,RJ,Brazil,20040-020,+55 (21) 2271-7000,+55 (21) 2271-7070,roberto.almeida@riotur.gov.br,3
4,13,Fernanda,Ramos,BaekSu,Qe 7 Bloco G,Brasília,DF,Brazil,71020-677,+55 (61) 3363-5547,+55 (61) 3363-7855,fernadaramos4@uol.com.br,4

# ORDER BY

In [23]:
statement = """
    SELECT * FROM Customers
    ORDER BY Country DESC, LastName
"""

run_sql(statement)

,CustomerId,FirstName,LastName,Company,Address,City,State,Country,PostalCode,Phone,Fax,Email,SupportRepId
0,53,Phil,Hughes,BaekSu,113 Lupus St,London,None,United Kingdom,SW1V 3EN,+44 020 7976 5722,None,phil.hughes@gmail.com,3
1,52,Emma,Jones,BaekSu,202 Hoxton Street,London,None,United Kingdom,N1 5LH,+44 020 7707 0707,None,emma_jones@hotmail.com,3
2,54,Steve,Murray,BaekSu,110 Raeburn Pl,Edinburgh,None,United Kingdom,EH4 1HH,+44 0131 315 3300,None,steve.murray@yahoo.uk,5
3,28,Julia,Barnett,BaekSu,302 S 700 E,Salt Lake City,UT,USA,84102,+1 (801) 531-7272,None,jubarnett@gmail.com,5
4,18,Michelle,Brooks,BaekSu,627 Broadway,New York,NY,USA,10012-2612,+1 (212) 221-3546,+1 (212) 221-4679,michelleb@aol.com,3
5,21,Kathy,Chase,BaekSu,801 W 4th Street,Reno,NV,USA,89503,+1 (775) 223-7665,None,kachase@hotmail.com,5
6,26,Richard,Cunningham,BaekSu,2211 W Berry Street,Fort Worth,TX,USA,76110,+1 (817) 924-7272,None,ricunningham@hotmail.com,4
7,23,John,Gordon,BaekSu,69 Salem Street,Boston,MA,USA,2113,+1 (617) 522-1333,None,johngordon22@yahoo.com,4
8,19,Tim,Goyer,Apple Inc.,1 Infinite Loop,Cupertino,CA,USA,95014,+1 (408) 996-1010,+1 (408) 996-1011,tgoyer@apple.com,3
9,27,Patrick,Gray,BaekSu,1033 N Park Ave,Tucson,AZ,USA,85719,+1 (520) 622-4200,None,patrick.gray@aol.com,4
10,16,Frank,Harris,Google Inc.,1600 Amphitheatre Parkway,Mountain View,CA,USA,94043-1351,+1 (650) 253-0000,+1 (650) 253-0000,fharris@google.com,4
11,22,Heather,Leacock,BaekSu,120 S Orange Ave,Orlando,FL,USA,32801,+1 (407) 999-7788,None,hleacock@gmail.com,4
12,20,Dan,Miller,BaekSu,541 Del Medio Avenue,Mountain View,CA,USA,94040-111,+1 (650) 644-3358,None,dmiller@comcast.com,4
13,24,Frank,Ralston,BaekSu,162 E Superior Street,Chicago,IL,USA,60611,+1 (312) 332-3232,None,fralston@gmail.com,3
14,17,Jack,Smith,Microsoft Corporation,1 Microsoft Way,Redmond,WA,USA,98052-8300,+1 (425) 882-8080,+1 (425) 882-8081,jacksmith@microsoft.com,5
15,25,Victor,Stevens,BaekSu,319 N. Frances Street,Madison,WI,USA,53703,+1 (608) 257-0597,None,vstevens@yahoo.com,5
16,51,Joakim,Johansson,BaekSu,Celsiusg. 9,Stockholm,None,Sweden,11230,+46 08-651 52 52,None,joakim.johansson@yahoo.se,5
17,50,Enrique,Muñoz,BaekSu,C/ San Bernardo 85,Madrid,None,Spain,28015,+34 914 454 454,None,enrique_munoz@yahoo.es,5
18,34,João,Fernandes,BaekSu,Rua da Assunção 53,Lisbon,None,Portugal,None,+351 (213) 466-111,None,jfernandes@yahoo.pt,4
19,35,Madalena,Sampaio,BaekSu,"Rua dos Campeões Europeus de Viena, 4350",Porto,None,Portugal,None,+351 (225) 022-448,None,masampaio@sapo.pt,4
20,49,Stanisław,Wójcik,BaekSu,Ordynacka 10,Warsaw,None,Poland,00-358,+48 22 828 37 39,None,stanisław.wójcik@wp.pl,4
21,4,Bjørn,Hansen,BaekSu,Ullevålsveien 14,Oslo,None,Norway,0171,+47 22 44 22 22,None,bjorn.hansen@yahoo.no,4
22,48,Johannes,Van der Berg,BaekSu,Lijnbaansgracht 120bg,Amsterdam,VV,Netherlands,1016,+31 020 6223130,None,johavanderberg@yahoo.nl,5
23,47,Lucas,Mancini,BaekSu,"Via Degli Scipioni, 43",Rome,RM,Italy,00192,+39 06 39733434,None,lucas.mancini@yahoo.it,5
24,46,Hugh,O'Reilly,BaekSu,3 Chatham Street,Dublin,Dublin,Ireland,None,+353 01 6792424,None,hughoreilly@apple.ie,3
25,58,Manoj,Pareek,BaekSu,"12,Community Centre",Delhi,None,India,110017,+91 0124 39883988,None,manoj.pareek@rediff.com,3
26,59,Puja,Srivastava,BaekSu,"3,Raj Bhavan Road",Bangalore,None,India,560001,+91 080 22289999,None,puja_srivastava@yahoo.in,3
27,45,Ladislav,Kovács,BaekSu,Erzsébet krt. 58.,Budapest,None,Hungary,H-1073,None,None,ladislav_kovacs@apple.hu,3
28,2,Leonie,Köhler,BaekSu,Theodor-Heuss-Straße 34,Stuttgart,None,Germany,70174,+49 0711 2842222,None,leonekohler@surfeu.de,5
29,36,Hannah,Schneider,BaekSu,Tauentzienstraße 8,Berlin,None,Germany,10789,+49 030 26550280,None,hannah.schneider@yahoo.de,5
30,38,Niklas,Schröder,BaekSu,Barbarossastraße 19,Berlin,None,Germany,10779,+49 030 2141444,None,nschroder@surfeu.de,3
31,37,Fynn,Zimmermann,BaekSu,Berger Straße 10,Frankfurt,None,Germany,60316,+49 069 40598889,None,fzimmermann@yahoo.de,3
32,39,Camille,Bernard,BaekSu,"4, Rue Milton",Paris,None,France,75009,+33 01 49 70 65 65,None,camille.bernard@yahoo.fr,4
33,41,Marc,Dubois,BaekSu,"11, Place Bellecour",Lyon,None,France,69002,+33 04 78 30 30 30,None,marc.dubois@hotmail.com,5
34,42,Wyatt,Girard,BaekSu,"9, Place Louis Barthou",Bordeaux,None,France,33000,+33 05 56 96 96 96,None,wyatt.girard@yahoo.fr,3
35,40,Dominique,Lefebvre,BaekSu,"8, Rue Hanovre",Paris,None,France,75002,+33 01 47 42 71 71,None,dominiquelefebvre@gmail.com,4
36,43,Isabelle,Mercier,BaekSu,"68, Rue Jouvence",Dijon,None,France,21000,+33 03 80 73 66 99,None,isabelle_mercier@apple.fr,3
37,44,Terhi,Hämäläinen,BaekSu,Porthaninkatu 9,Helsinki,None,Finland,00530,+358 09 870 2000,None,terhi.hamalainen@apple.fi,3
38,9,Kara,Nielsen,BaekSu,Sønder Boulevard 51,Copenhagen,None,Denmark,1720,+453 3331 9991,None,kara.nielsen@jubii.dk,4
39,6,Helena,Holý,BaekSu,Rilská 3174/6,Prague,None,Czech Republic,14300,+420 2 4177 0449,None,hholy@gmail.com,5
40,5,František,Wichterlová,JetBrains s.r.o.,Klanova 9/506,Prague,None,Czech Republic,14700,+420 2 4172 5555,+420 2 4172 5555,frantisekw@jetbrains.com,4
41,57,Luis,Rojas,BaekSu,"Calle Lira, 198",Santiago,None,Chile,None,+56 (0)2 635 4444,None,luisrojas@yahoo.cl,5
42,29,Robert,Brown,BaekSu,796 Dundas Street West,Toronto,ON,Canada,M6J 1V1,+1 (416) 363-8888,None,robbrown@shaw.ca,3
43,30,Edward,Francis,BaekSu,230 Elgin Street,Ottawa,ON,Canada,K2P 1L7,+1 (613) 234-3322,None,edfrancis@yachoo.ca,3
44,32,Aaron,Mitchell,BaekSu,696 Osborne Street,Winnipeg,MB,Canada,R3L 2B9,+1 (204) 452-6452,None,aaronmitchell@yahoo.ca,4
45,15,Jennifer,Peterson,Rogers Canada,700 W Pender Street,Vancouver,BC,Canada,V6C 1G8,+1 (604) 688-2255,+1 (604) 688-8756,jenniferp@rogers.ca,3
46,14,Mark,Philips,Telus,8210 111 ST NW,Edmonton,AB,Canada,T6G 2C7,+1 (780) 434-4554,+1 (780) 434-5565,mphilips12@shaw.ca,5
47,31,Martha,Silk,BaekSu,194A Chain Lake Drive,Halifax,NS,Canada,B3S 1C5,+1 (902) 450-0450,None,marthasilk@gmail.com,5
48,33,Ellie,Sullivan,BaekSu,5112 48 Street,Yellowknife,NT,Canada,X1A 1N6,+1 (867) 920-2233,None,ellie.sullivan@shaw.ca,3
49,3,François,Tremblay,BaekSu,1498 rue Bélanger,Montréal,QC,Canada,H2G 1A7,+1 (514) 721-4711,None,ftremblay@gmail.com,3
50,12,Roberto,Almeida,Riotur,"Praça Pio X, 119",Rio de Janeiro,RJ,Brazil,20040-020,+55 (21) 2271-7000,+55 (21) 2271-7070,roberto.almeida@riotur.gov.br,3
51,1,Luís,Gonçalves,Embraer - Empresa Brasileira de Aeronáutica S.A.,"Av. Brigadeiro Faria Lima, 2170",São José dos Campos,SP,Brazil,12227-000,+55 (12) 3923-5555,+55 (12) 3923-5566,luisg@embraer.com.br,3
52,10,Eduardo,Martins,Woodstock Discos,"Rua Dr. Falcão Filho, 155",São Paulo,SP,Brazil,01007-010,+55 (11) 3033-5446,+55 (11) 3033-4564,eduardo@woodstock.com.br,4
53,13,Fernanda,Ramos,BaekSu,Qe 7 Bloco G,Brasília,DF,Brazil,71020-677,+55 (61) 3363-5547,+55 (61) 3363-7855,fernadaramos4@uol.com.br,4
54,11,Alexandre,Rocha,Banco do Brasil S.A.,"Av. Paulista, 2022",São Paulo,SP,Brazil,01310-200,+55 (11) 3055-3278,+55 (11) 3055-8131,alero@uol.com.br,5
55,8,Daan,Peeters,BaekSu,Grétrystraat 63,Brussels,None,Belgium,1000,+32 02 219 03 03,None,daan_peeters@apple.be,4
56,7,Astrid,Gruber,BaekSu,"Rotenturmstraße 4, 1010 Innere Stadt",Vienne,None,Austria,1010,+43 01 5134505,None,astrid.gruber@apple.at,5
57,55,Mark,Taylor,BaekSu,421 Bourke Street,Sidney,NSW,Australia,2010,+61 (02) 9332 3633,None,mark.taylor@yahoo.au,4
58,56,Diego,Gutiérrez,BaekSu,307 Macacha Güemes,Buenos Aires,None,Argentina,1106,+54 (0)11 4311 4333,None,diego.gutierrez@yahoo.ar,4

# AND OR NOT

In [26]:
statement = """
    SELECT * FROM Customers
    WHERE Country='India' AND LastName LIKE 'P%'
"""

run_sql(statement)

,CustomerId,FirstName,LastName,Company,Address,City,State,Country,PostalCode,Phone,Fax,Email,SupportRepId
0,58,Manoj,Pareek,BaekSu,"12,Community Centre",Delhi,None,India,110017,+91 0124 39883988,None,manoj.pareek@rediff.com,3

In [28]:
statement = """
    SELECT * FROM Customers
    WHERE Country='India' OR Country='Brazil'
"""

run_sql(statement)

,CustomerId,FirstName,LastName,Company,Address,City,State,Country,PostalCode,Phone,Fax,Email,SupportRepId
0,1,Luís,Gonçalves,Embraer - Empresa Brasileira de Aeronáutica S.A.,"Av. Brigadeiro Faria Lima, 2170",São José dos Campos,SP,Brazil,12227-000,+55 (12) 3923-5555,+55 (12) 3923-5566,luisg@embraer.com.br,3
1,10,Eduardo,Martins,Woodstock Discos,"Rua Dr. Falcão Filho, 155",São Paulo,SP,Brazil,01007-010,+55 (11) 3033-5446,+55 (11) 3033-4564,eduardo@woodstock.com.br,4
2,11,Alexandre,Rocha,Banco do Brasil S.A.,"Av. Paulista, 2022",São Paulo,SP,Brazil,01310-200,+55 (11) 3055-3278,+55 (11) 3055-8131,alero@uol.com.br,5
3,12,Roberto,Almeida,Riotur,"Praça Pio X, 119",Rio de Janeiro,RJ,Brazil,20040-020,+55 (21) 2271-7000,+55 (21) 2271-7070,roberto.almeida@riotur.gov.br,3
4,13,Fernanda,Ramos,BaekSu,Qe 7 Bloco G,Brasília,DF,Brazil,71020-677,+55 (61) 3363-5547,+55 (61) 3363-7855,fernadaramos4@uol.com.br,4
5,58,Manoj,Pareek,BaekSu,"12,Community Centre",Delhi,None,India,110017,+91 0124 39883988,None,manoj.pareek@rediff.com,3
6,59,Puja,Srivastava,BaekSu,"3,Raj Bhavan Road",Bangalore,None,India,560001,+91 080 22289999,None,puja_srivastava@yahoo.in,3

# INSERT INTO

In [31]:
statement = """
    INSERT INTO Customers (FirstName, LastName, Company, Country, Email)
    VALUES ('Gildong', 'Hong', 'Hyundai Motors Group', 'Republic of Korea', 'a@b.com');
"""

run_sql(statement)

statement = """
    SELECT * FROM Customers
    WHERE FirstName='Gildong';
"""

run_sql(statement)

,CustomerId,FirstName,LastName,Company,Address,City,State,Country,PostalCode,Phone,Fax,Email,SupportRepId
0,64,Gildong,Hong,Hyundai Motors Group,None,None,None,Republic of Korea,None,None,None,a@b.com,None

# NULL Values

In [34]:
statement = """
    SELECT FirstName, LastName FROM Customers
    WHERE Company IS NOT NULL;
"""

run_sql(statement)

    FirstName      LastName
0        Luís     Gonçalves
1      Leonie        Köhler
2    François      Tremblay
3       Bjørn        Hansen
4   František   Wichterlová
5      Helena          Holý
6      Astrid        Gruber
7        Daan       Peeters
8        Kara       Nielsen
9     Eduardo       Martins
10  Alexandre         Rocha
11    Roberto       Almeida
12   Fernanda         Ramos
13       Mark       Philips
14   Jennifer      Peterson
15      Frank        Harris
16       Jack         Smith
17   Michelle        Brooks
18        Tim         Goyer
19        Dan        Miller
20      Kathy         Chase
21    Heather       Leacock
22       John        Gordon
23      Frank       Ralston
24     Victor       Stevens
25    Richard    Cunningham
26    Patrick          Gray
27      Julia       Barnett
28     Robert         Brown
29     Edward       Francis
30     Martha          Silk
31      Aaron      Mitchell
32      Ellie      Sullivan
33       João     Fernandes
34   Madalena       Sampaio
35     Hannah     Schneider
36       Fynn    Zimmermann
37     Niklas      Schröder
38    Camille       Bernard
39  Dominique      Lefebvre
40       Marc        Dubois
41      Wyatt        Girard
42   Isabelle       Mercier
43      Terhi    Hämäläinen
44   Ladislav        Kovács
45       Hugh      O'Reilly
46      Lucas       Mancini
47   Johannes  Van der Berg
48  Stanisław        Wójcik
49    Enrique         Muñoz
50     Joakim     Johansson
51       Emma         Jones
52       Phil        Hughes
53      Steve        Murray
54       Mark        Taylor
55      Diego     Gutiérrez
56       Luis         Rojas
57      Manoj        Pareek
58       Puja    Srivastava
59    Gildong          Hong

# UPDATE

In [37]:
statement = """
    UPDATE Customers
    SET Company='BaekSu'
    WHERE Company IS NULL
"""

run_sql(statement)

statement = """
    SELECT * FROM Customers
"""

run_sql(statement)

,CustomerId,FirstName,LastName,Company,Address,City,State,Country,PostalCode,Phone,Fax,Email,SupportRepId
0,1,Luís,Gonçalves,Embraer - Empresa Brasileira de Aeronáutica S.A.,"Av. Brigadeiro Faria Lima, 2170",São José dos Campos,SP,Brazil,12227-000,+55 (12) 3923-5555,+55 (12) 3923-5566,luisg@embraer.com.br,3.0
1,2,Leonie,Köhler,BaekSu,Theodor-Heuss-Straße 34,Stuttgart,None,Germany,70174,+49 0711 2842222,None,leonekohler@surfeu.de,5.0
2,3,François,Tremblay,BaekSu,1498 rue Bélanger,Montréal,QC,Canada,H2G 1A7,+1 (514) 721-4711,None,ftremblay@gmail.com,3.0
3,4,Bjørn,Hansen,BaekSu,Ullevålsveien 14,Oslo,None,Norway,0171,+47 22 44 22 22,None,bjorn.hansen@yahoo.no,4.0
4,5,František,Wichterlová,JetBrains s.r.o.,Klanova 9/506,Prague,None,Czech Republic,14700,+420 2 4172 5555,+420 2 4172 5555,frantisekw@jetbrains.com,4.0
5,6,Helena,Holý,BaekSu,Rilská 3174/6,Prague,None,Czech Republic,14300,+420 2 4177 0449,None,hholy@gmail.com,5.0
6,7,Astrid,Gruber,BaekSu,"Rotenturmstraße 4, 1010 Innere Stadt",Vienne,None,Austria,1010,+43 01 5134505,None,astrid.gruber@apple.at,5.0
7,8,Daan,Peeters,BaekSu,Grétrystraat 63,Brussels,None,Belgium,1000,+32 02 219 03 03,None,daan_peeters@apple.be,4.0
8,9,Kara,Nielsen,BaekSu,Sønder Boulevard 51,Copenhagen,None,Denmark,1720,+453 3331 9991,None,kara.nielsen@jubii.dk,4.0
9,10,Eduardo,Martins,Woodstock Discos,"Rua Dr. Falcão Filho, 155",São Paulo,SP,Brazil,01007-010,+55 (11) 3033-5446,+55 (11) 3033-4564,eduardo@woodstock.com.br,4.0
10,11,Alexandre,Rocha,Banco do Brasil S.A.,"Av. Paulista, 2022",São Paulo,SP,Brazil,01310-200,+55 (11) 3055-3278,+55 (11) 3055-8131,alero@uol.com.br,5.0
11,12,Roberto,Almeida,Riotur,"Praça Pio X, 119",Rio de Janeiro,RJ,Brazil,20040-020,+55 (21) 2271-7000,+55 (21) 2271-7070,roberto.almeida@riotur.gov.br,3.0
12,13,Fernanda,Ramos,BaekSu,Qe 7 Bloco G,Brasília,DF,Brazil,71020-677,+55 (61) 3363-5547,+55 (61) 3363-7855,fernadaramos4@uol.com.br,4.0
13,14,Mark,Philips,Telus,8210 111 ST NW,Edmonton,AB,Canada,T6G 2C7,+1 (780) 434-4554,+1 (780) 434-5565,mphilips12@shaw.ca,5.0
14,15,Jennifer,Peterson,Rogers Canada,700 W Pender Street,Vancouver,BC,Canada,V6C 1G8,+1 (604) 688-2255,+1 (604) 688-8756,jenniferp@rogers.ca,3.0
15,16,Frank,Harris,Google Inc.,1600 Amphitheatre Parkway,Mountain View,CA,USA,94043-1351,+1 (650) 253-0000,+1 (650) 253-0000,fharris@google.com,4.0
16,17,Jack,Smith,Microsoft Corporation,1 Microsoft Way,Redmond,WA,USA,98052-8300,+1 (425) 882-8080,+1 (425) 882-8081,jacksmith@microsoft.com,5.0
17,18,Michelle,Brooks,BaekSu,627 Broadway,New York,NY,USA,10012-2612,+1 (212) 221-3546,+1 (212) 221-4679,michelleb@aol.com,3.0
18,19,Tim,Goyer,Apple Inc.,1 Infinite Loop,Cupertino,CA,USA,95014,+1 (408) 996-1010,+1 (408) 996-1011,tgoyer@apple.com,3.0
19,20,Dan,Miller,BaekSu,541 Del Medio Avenue,Mountain View,CA,USA,94040-111,+1 (650) 644-3358,None,dmiller@comcast.com,4.0
20,21,Kathy,Chase,BaekSu,801 W 4th Street,Reno,NV,USA,89503,+1 (775) 223-7665,None,kachase@hotmail.com,5.0
21,22,Heather,Leacock,BaekSu,120 S Orange Ave,Orlando,FL,USA,32801,+1 (407) 999-7788,None,hleacock@gmail.com,4.0
22,23,John,Gordon,BaekSu,69 Salem Street,Boston,MA,USA,2113,+1 (617) 522-1333,None,johngordon22@yahoo.com,4.0
23,24,Frank,Ralston,BaekSu,162 E Superior Street,Chicago,IL,USA,60611,+1 (312) 332-3232,None,fralston@gmail.com,3.0
24,25,Victor,Stevens,BaekSu,319 N. Frances Street,Madison,WI,USA,53703,+1 (608) 257-0597,None,vstevens@yahoo.com,5.0
25,26,Richard,Cunningham,BaekSu,2211 W Berry Street,Fort Worth,TX,USA,76110,+1 (817) 924-7272,None,ricunningham@hotmail.com,4.0
26,27,Patrick,Gray,BaekSu,1033 N Park Ave,Tucson,AZ,USA,85719,+1 (520) 622-4200,None,patrick.gray@aol.com,4.0
27,28,Julia,Barnett,BaekSu,302 S 700 E,Salt Lake City,UT,USA,84102,+1 (801) 531-7272,None,jubarnett@gmail.com,5.0
28,29,Robert,Brown,BaekSu,796 Dundas Street West,Toronto,ON,Canada,M6J 1V1,+1 (416) 363-8888,None,robbrown@shaw.ca,3.0
29,30,Edward,Francis,BaekSu,230 Elgin Street,Ottawa,ON,Canada,K2P 1L7,+1 (613) 234-3322,None,edfrancis@yachoo.ca,3.0
30,31,Martha,Silk,BaekSu,194A Chain Lake Drive,Halifax,NS,Canada,B3S 1C5,+1 (902) 450-0450,None,marthasilk@gmail.com,5.0
31,32,Aaron,Mitchell,BaekSu,696 Osborne Street,Winnipeg,MB,Canada,R3L 2B9,+1 (204) 452-6452,None,aaronmitchell@yahoo.ca,4.0
32,33,Ellie,Sullivan,BaekSu,5112 48 Street,Yellowknife,NT,Canada,X1A 1N6,+1 (867) 920-2233,None,ellie.sullivan@shaw.ca,3.0
33,34,João,Fernandes,BaekSu,Rua da Assunção 53,Lisbon,None,Portugal,None,+351 (213) 466-111,None,jfernandes@yahoo.pt,4.0
34,35,Madalena,Sampaio,BaekSu,"Rua dos Campeões Europeus de Viena, 4350",Porto,None,Portugal,None,+351 (225) 022-448,None,masampaio@sapo.pt,4.0
35,36,Hannah,Schneider,BaekSu,Tauentzienstraße 8,Berlin,None,Germany,10789,+49 030 26550280,None,hannah.schneider@yahoo.de,5.0
36,37,Fynn,Zimmermann,BaekSu,Berger Straße 10,Frankfurt,None,Germany,60316,+49 069 40598889,None,fzimmermann@yahoo.de,3.0
37,38,Niklas,Schröder,BaekSu,Barbarossastraße 19,Berlin,None,Germany,10779,+49 030 2141444,None,nschroder@surfeu.de,3.0
38,39,Camille,Bernard,BaekSu,"4, Rue Milton",Paris,None,France,75009,+33 01 49 70 65 65,None,camille.bernard@yahoo.fr,4.0
39,40,Dominique,Lefebvre,BaekSu,"8, Rue Hanovre",Paris,None,France,75002,+33 01 47 42 71 71,None,dominiquelefebvre@gmail.com,4.0
40,41,Marc,Dubois,BaekSu,"11, Place Bellecour",Lyon,None,France,69002,+33 04 78 30 30 30,None,marc.dubois@hotmail.com,5.0
41,42,Wyatt,Girard,BaekSu,"9, Place Louis Barthou",Bordeaux,None,France,33000,+33 05 56 96 96 96,None,wyatt.girard@yahoo.fr,3.0
42,43,Isabelle,Mercier,BaekSu,"68, Rue Jouvence",Dijon,None,France,21000,+33 03 80 73 66 99,None,isabelle_mercier@apple.fr,3.0
43,44,Terhi,Hämäläinen,BaekSu,Porthaninkatu 9,Helsinki,None,Finland,00530,+358 09 870 2000,None,terhi.hamalainen@apple.fi,3.0
44,45,Ladislav,Kovács,BaekSu,Erzsébet krt. 58.,Budapest,None,Hungary,H-1073,None,None,ladislav_kovacs@apple.hu,3.0
45,46,Hugh,O'Reilly,BaekSu,3 Chatham Street,Dublin,Dublin,Ireland,None,+353 01 6792424,None,hughoreilly@apple.ie,3.0
46,47,Lucas,Mancini,BaekSu,"Via Degli Scipioni, 43",Rome,RM,Italy,00192,+39 06 39733434,None,lucas.mancini@yahoo.it,5.0
47,48,Johannes,Van der Berg,BaekSu,Lijnbaansgracht 120bg,Amsterdam,VV,Netherlands,1016,+31 020 6223130,None,johavanderberg@yahoo.nl,5.0
48,49,Stanisław,Wójcik,BaekSu,Ordynacka 10,Warsaw,None,Poland,00-358,+48 22 828 37 39,None,stanisław.wójcik@wp.pl,4.0
49,50,Enrique,Muñoz,BaekSu,C/ San Bernardo 85,Madrid,None,Spain,28015,+34 914 454 454,None,enrique_munoz@yahoo.es,5.0
50,51,Joakim,Johansson,BaekSu,Celsiusg. 9,Stockholm,None,Sweden,11230,+46 08-651 52 52,None,joakim.johansson@yahoo.se,5.0
51,52,Emma,Jones,BaekSu,202 Hoxton Street,London,None,United Kingdom,N1 5LH,+44 020 7707 0707,None,emma_jones@hotmail.com,3.0
52,53,Phil,Hughes,BaekSu,113 Lupus St,London,None,United Kingdom,SW1V 3EN,+44 020 7976 5722,None,phil.hughes@gmail.com,3.0
53,54,Steve,Murray,BaekSu,110 Raeburn Pl,Edinburgh,None,United Kingdom,EH4 1HH,+44 0131 315 3300,None,steve.murray@yahoo.uk,5.0
54,55,Mark,Taylor,BaekSu,421 Bourke Street,Sidney,NSW,Australia,2010,+61 (02) 9332 3633,None,mark.taylor@yahoo.au,4.0
55,56,Diego,Gutiérrez,BaekSu,307 Macacha Güemes,Buenos Aires,None,Argentina,1106,+54 (0)11 4311 4333,None,diego.gutierrez@yahoo.ar,4.0
56,57,Luis,Rojas,BaekSu,"Calle Lira, 198",Santiago,None,Chile,None,+56 (0)2 635 4444,None,luisrojas@yahoo.cl,5.0
57,58,Manoj,Pareek,BaekSu,"12,Community Centre",Delhi,None,India,110017,+91 0124 39883988,None,manoj.pareek@rediff.com,3.0
58,59,Puja,Srivastava,BaekSu,"3,Raj Bhavan Road",Bangalore,None,India,560001,+91 080 22289999,None,puja_srivastava@yahoo.in,3.0
59,64,Gildong,Hong,Hyundai Motors Group,None,None,None,Republic of Korea,None,None,None,a@b.com,NaN

# DELETE

In [40]:
statement = """
    DELETE FROM Customers
    WHERE FirstName='Gildong';
"""

run_sql(statement)

statement = """
    SELECT * FROM Customers
    WHERE FirstName='Gildong';
"""

run_sql(statement)

Empty DataFrame
Columns: [CustomerId, FirstName, LastName, Company, Address, City, State, Country, PostalCode, Phone, Fax, Email, SupportRepId]
Index: []

# SELECT TOP, LIMIT, FETCH FIRST
TOP: MS SQL Server
LIMIT: MySQL
FETCH FIRST: Oracle

In [43]:
statement = """
    SELECT * FROM Customers
    LIMIT 3;
"""

run_sql(statement)

,CustomerId,FirstName,LastName,Company,Address,City,State,Country,PostalCode,Phone,Fax,Email,SupportRepId
0,1,Luís,Gonçalves,Embraer - Empresa Brasileira de Aeronáutica S.A.,"Av. Brigadeiro Faria Lima, 2170",São José dos Campos,SP,Brazil,12227-000,+55 (12) 3923-5555,+55 (12) 3923-5566,luisg@embraer.com.br,3
1,2,Leonie,Köhler,BaekSu,Theodor-Heuss-Straße 34,Stuttgart,None,Germany,70174,+49 0711 2842222,None,leonekohler@surfeu.de,5
2,3,François,Tremblay,BaekSu,1498 rue Bélanger,Montréal,QC,Canada,H2G 1A7,+1 (514) 721-4711,None,ftremblay@gmail.com,3

# MIN() MAX()

In [46]:
statement = """
    SELECT MIN(FirstName) AS FastestName
    FROM Customers;
"""

run_sql(statement)

  FastestName
0       Aaron

# COUNT(), AVG(), SUM()

In [49]:
# fax번호가 null이 아닌 미국인 수
statement = """
    SELECT COUNT(Fax)
    FROM Customers
    WHERE Country='USA';
"""

run_sql(statement)

   COUNT(Fax)
0           4

In [55]:
statement = """
    SELECT COUNT(DISTINCT Country) AS [Number of Countries]
    From Customers;
"""

run_sql(statement)

   Number of Countries
0                   24

In [57]:
statement = """
    SELECT SUM(SupportRepId) AS SumOfSupportRepId
    FROM Customers;
"""

run_sql(statement)

   SumOfSupportRepId
0                233

In [61]:
statement = """
    SELECT AVG(SupportRepId) AS AverageOfSupportRepId
    FROM Customers
    WHERE Country='Brazil';
"""

run_sql(statement)

   AverageOfSupportRepId
0                    3.8

In [71]:
statement = """
    SELECT AVG(UnitPrice)
    FROM Invoice_Items;
"""

run_sql(statement)

   AVG(UnitPrice)
0        1.039554

# LIKE

In [104]:
# select all customers that have 'e' in the second position
statement = """
    SELECT * FROM Customers
    WHERE FirstName LIKE '_e%';
"""

run_sql(statement)

,CustomerId,FirstName,LastName,Company,Address,City,State,Country,PostalCode,Phone,Fax,Email,SupportRepId
0,2,Leonie,Köhler,BaekSu,Theodor-Heuss-Straße 34,Stuttgart,None,Germany,70174,+49 0711 2842222,None,leonekohler@surfeu.de,5
1,6,Helena,Holý,BaekSu,Rilská 3174/6,Prague,None,Czech Republic,14300,+420 2 4177 0449,None,hholy@gmail.com,5
2,13,Fernanda,Ramos,BaekSu,Qe 7 Bloco G,Brasília,DF,Brazil,71020-677,+55 (61) 3363-5547,+55 (61) 3363-7855,fernadaramos4@uol.com.br,4
3,15,Jennifer,Peterson,Rogers Canada,700 W Pender Street,Vancouver,BC,Canada,V6C 1G8,+1 (604) 688-2255,+1 (604) 688-8756,jenniferp@rogers.ca,3
4,22,Heather,Leacock,BaekSu,120 S Orange Ave,Orlando,FL,USA,32801,+1 (407) 999-7788,None,hleacock@gmail.com,4
5,44,Terhi,Hämäläinen,BaekSu,Porthaninkatu 9,Helsinki,None,Finland,00530,+358 09 870 2000,None,terhi.hamalainen@apple.fi,3

# Wildcards

sqlite에서는 glob 사용해서 더 다양하게 할 수 있음\
https://www.sqlitetutorial.net/sqlite-glob/

|Symbol|Description
-----|-----
%	|Represents zero or more characters
_	|Represents a single character
[]	|Represents any single character within the brackets *
^	|Represents any character not in the brackets *
-	|Represents any single character within the specified range *
{}	|Represents any escaped character **

\* Not supported in PostgreSQL and MySQL databases.\
** Supported only in Oracle databases.

In [130]:
# select all customers whose first name is not start with A to T
statement = """
    SELECT * FROM Customers
    WHERE FirstName GLOB '[^A-T]*';
"""

run_sql(statement)

,CustomerId,FirstName,LastName,Company,Address,City,State,Country,PostalCode,Phone,Fax,Email,SupportRepId
0,25,Victor,Stevens,BaekSu,319 N. Frances Street,Madison,WI,USA,53703,+1 (608) 257-0597,None,vstevens@yahoo.com,5
1,42,Wyatt,Girard,BaekSu,"9, Place Louis Barthou",Bordeaux,None,France,33000,+33 05 56 96 96 96,None,wyatt.girard@yahoo.fr,3

# IN

In [132]:
statement = """
    SELECT * FROM Customers
    WHERE Country In ('Germany', 'United Kingdom')
"""

run_sql(statement)

,CustomerId,FirstName,LastName,Company,Address,City,State,Country,PostalCode,Phone,Fax,Email,SupportRepId
0,2,Leonie,Köhler,BaekSu,Theodor-Heuss-Straße 34,Stuttgart,None,Germany,70174,+49 0711 2842222,None,leonekohler@surfeu.de,5
1,36,Hannah,Schneider,BaekSu,Tauentzienstraße 8,Berlin,None,Germany,10789,+49 030 26550280,None,hannah.schneider@yahoo.de,5
2,37,Fynn,Zimmermann,BaekSu,Berger Straße 10,Frankfurt,None,Germany,60316,+49 069 40598889,None,fzimmermann@yahoo.de,3
3,38,Niklas,Schröder,BaekSu,Barbarossastraße 19,Berlin,None,Germany,10779,+49 030 2141444,None,nschroder@surfeu.de,3
4,52,Emma,Jones,BaekSu,202 Hoxton Street,London,None,United Kingdom,N1 5LH,+44 020 7707 0707,None,emma_jones@hotmail.com,3
5,53,Phil,Hughes,BaekSu,113 Lupus St,London,None,United Kingdom,SW1V 3EN,+44 020 7976 5722,None,phil.hughes@gmail.com,3
6,54,Steve,Murray,BaekSu,110 Raeburn Pl,Edinburgh,None,United Kingdom,EH4 1HH,+44 0131 315 3300,None,steve.murray@yahoo.uk,5

# BETWEEN

In [137]:
statement = """
    SELECT * FROM Customers
    WHERE Country BETWEEN 'Germany' AND 'United Kingdom'
"""

run_sql(statement)

,CustomerId,FirstName,LastName,Company,Address,City,State,Country,PostalCode,Phone,Fax,Email,SupportRepId
0,2,Leonie,Köhler,BaekSu,Theodor-Heuss-Straße 34,Stuttgart,None,Germany,70174,+49 0711 2842222,None,leonekohler@surfeu.de,5
1,4,Bjørn,Hansen,BaekSu,Ullevålsveien 14,Oslo,None,Norway,0171,+47 22 44 22 22,None,bjorn.hansen@yahoo.no,4
2,16,Frank,Harris,Google Inc.,1600 Amphitheatre Parkway,Mountain View,CA,USA,94043-1351,+1 (650) 253-0000,+1 (650) 253-0000,fharris@google.com,4
3,17,Jack,Smith,Microsoft Corporation,1 Microsoft Way,Redmond,WA,USA,98052-8300,+1 (425) 882-8080,+1 (425) 882-8081,jacksmith@microsoft.com,5
4,18,Michelle,Brooks,BaekSu,627 Broadway,New York,NY,USA,10012-2612,+1 (212) 221-3546,+1 (212) 221-4679,michelleb@aol.com,3
5,19,Tim,Goyer,Apple Inc.,1 Infinite Loop,Cupertino,CA,USA,95014,+1 (408) 996-1010,+1 (408) 996-1011,tgoyer@apple.com,3
6,20,Dan,Miller,BaekSu,541 Del Medio Avenue,Mountain View,CA,USA,94040-111,+1 (650) 644-3358,None,dmiller@comcast.com,4
7,21,Kathy,Chase,BaekSu,801 W 4th Street,Reno,NV,USA,89503,+1 (775) 223-7665,None,kachase@hotmail.com,5
8,22,Heather,Leacock,BaekSu,120 S Orange Ave,Orlando,FL,USA,32801,+1 (407) 999-7788,None,hleacock@gmail.com,4
9,23,John,Gordon,BaekSu,69 Salem Street,Boston,MA,USA,2113,+1 (617) 522-1333,None,johngordon22@yahoo.com,4
10,24,Frank,Ralston,BaekSu,162 E Superior Street,Chicago,IL,USA,60611,+1 (312) 332-3232,None,fralston@gmail.com,3
11,25,Victor,Stevens,BaekSu,319 N. Frances Street,Madison,WI,USA,53703,+1 (608) 257-0597,None,vstevens@yahoo.com,5
12,26,Richard,Cunningham,BaekSu,2211 W Berry Street,Fort Worth,TX,USA,76110,+1 (817) 924-7272,None,ricunningham@hotmail.com,4
13,27,Patrick,Gray,BaekSu,1033 N Park Ave,Tucson,AZ,USA,85719,+1 (520) 622-4200,None,patrick.gray@aol.com,4
14,28,Julia,Barnett,BaekSu,302 S 700 E,Salt Lake City,UT,USA,84102,+1 (801) 531-7272,None,jubarnett@gmail.com,5
15,34,João,Fernandes,BaekSu,Rua da Assunção 53,Lisbon,None,Portugal,None,+351 (213) 466-111,None,jfernandes@yahoo.pt,4
16,35,Madalena,Sampaio,BaekSu,"Rua dos Campeões Europeus de Viena, 4350",Porto,None,Portugal,None,+351 (225) 022-448,None,masampaio@sapo.pt,4
17,36,Hannah,Schneider,BaekSu,Tauentzienstraße 8,Berlin,None,Germany,10789,+49 030 26550280,None,hannah.schneider@yahoo.de,5
18,37,Fynn,Zimmermann,BaekSu,Berger Straße 10,Frankfurt,None,Germany,60316,+49 069 40598889,None,fzimmermann@yahoo.de,3
19,38,Niklas,Schröder,BaekSu,Barbarossastraße 19,Berlin,None,Germany,10779,+49 030 2141444,None,nschroder@surfeu.de,3
20,45,Ladislav,Kovács,BaekSu,Erzsébet krt. 58.,Budapest,None,Hungary,H-1073,None,None,ladislav_kovacs@apple.hu,3
21,46,Hugh,O'Reilly,BaekSu,3 Chatham Street,Dublin,Dublin,Ireland,None,+353 01 6792424,None,hughoreilly@apple.ie,3
22,47,Lucas,Mancini,BaekSu,"Via Degli Scipioni, 43",Rome,RM,Italy,00192,+39 06 39733434,None,lucas.mancini@yahoo.it,5
23,48,Johannes,Van der Berg,BaekSu,Lijnbaansgracht 120bg,Amsterdam,VV,Netherlands,1016,+31 020 6223130,None,johavanderberg@yahoo.nl,5
24,49,Stanisław,Wójcik,BaekSu,Ordynacka 10,Warsaw,None,Poland,00-358,+48 22 828 37 39,None,stanisław.wójcik@wp.pl,4
25,50,Enrique,Muñoz,BaekSu,C/ San Bernardo 85,Madrid,None,Spain,28015,+34 914 454 454,None,enrique_munoz@yahoo.es,5
26,51,Joakim,Johansson,BaekSu,Celsiusg. 9,Stockholm,None,Sweden,11230,+46 08-651 52 52,None,joakim.johansson@yahoo.se,5
27,52,Emma,Jones,BaekSu,202 Hoxton Street,London,None,United Kingdom,N1 5LH,+44 020 7707 0707,None,emma_jones@hotmail.com,3
28,53,Phil,Hughes,BaekSu,113 Lupus St,London,None,United Kingdom,SW1V 3EN,+44 020 7976 5722,None,phil.hughes@gmail.com,3
29,54,Steve,Murray,BaekSu,110 Raeburn Pl,Edinburgh,None,United Kingdom,EH4 1HH,+44 0131 315 3300,None,steve.murray@yahoo.uk,5
30,58,Manoj,Pareek,BaekSu,"12,Community Centre",Delhi,None,India,110017,+91 0124 39883988,None,manoj.pareek@rediff.com,3
31,59,Puja,Srivastava,BaekSu,"3,Raj Bhavan Road",Bangalore,None,India,560001,+91 080 22289999,None,puja_srivastava@yahoo.in,3

# Aliases

# Joins

# UNION

# GROUP BY

# HAVING

# EXISTS

# ANY and ALL

# CASE

# Comments